-- =============================================================================
-- Prueba CCL — base `ccl_inventario`, tabla `productos` y datos iniciales (manual).
--
-- Orden (pgAdmin / DBeaver / etc.):
--   1) Conectado a la base del sistema "postgres": ejecutar solo el BLOQUE 1
--      (hasta el separador). Si la base ya existe, omita el BLOQUE 1.
--   2) Conectado a "ccl_inventario": ejecutar del BLOQUE 2 hasta el final.
--
-- Si ejecuta el archivo entero estando en "postgres", el BLOQUE 2 abortará
-- a propósito para no crear la tabla en la base incorrecta.
--
-- Alternativa: arrancar la API una vez (EnsureCreated) y en "ccl_inventario"
-- ejecutar solo el BLOQUE 3 (omitir 1 y 2 si la tabla ya existe).
-- =============================================================================

-- ========== BLOQUE 1 — solo conectado a la base "postgres" ==========

CREATE DATABASE ccl_inventario
    ENCODING 'UTF8';

-- ========== BLOQUE 2 y 3 — solo conectado a la base "ccl_inventario" ==========

DO $guard$
BEGIN
  IF current_database() IS DISTINCT FROM 'ccl_inventario' THEN
    RAISE EXCEPTION
      'Ejecute el BLOQUE 2 y 3 estando conectado a la base ''ccl_inventario'' (base actual: %). Cree la BD con el BLOQUE 1 en ''postgres'' y vuelva a conectar.',
      current_database();
  END IF;
END
$guard$;

CREATE TABLE IF NOT EXISTS productos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(200) NOT NULL,
    cantidad integer NOT NULL
);

INSERT INTO productos (nombre, cantidad)
SELECT v.nombre, v.cantidad
FROM (VALUES
  ('Resma papel A4', 120),
  ('Bolígrafo azul', 300),
  ('Tóner impresora', 15)
) AS v(nombre, cantidad)
WHERE NOT EXISTS (SELECT 1 FROM productos);
